
export const ClubCsvName = {
    'XXX': 'その他',
    'PT': 'パター',
    '9WG': '60°',
    '8WG': '58°',
    '7WG': '56°',
    '6WG': '54°',
    '5WG': '52°',
    '4WG': '50°',
    'LW': 'ピッチングウェッジ',
    'SW': 'サンドウェッジ',
    'PW': 'ロブウェッジ',
    '9I': '9 iron',
    '8I': '8 iron',
    '7I': '7 iron',
    '6I': '6 iron',
    '5I': '5 iron',
    '4I': '4 iron',
    '3I': '3 iron',
    '2I': '2 iron',
    '1I': '1 iron',
    '9UT': '9 ut',
    '8UT': '8 ut',
    '7UT': '7 ut',
    '6UT': '6 ut',
    '5UT': '5 ut',
    '4UT': '4 ut',
    '3UT': '3 ut',
    '2UT': '2 ut',
    '1UT': '1 ut',
    '9W': '9 wood',
    '8W': '8 wood',
    '7W': '7 wood',
    '6W': '6 wood',
    '5W': '5 wood',
    '4W': '4 wood',
    '3W': '3 wood',
    '2W': '2 wood',
    'DR': 'ドライバー',
} as const

export type ClubCsvNames = typeof ClubCsvName[keyof typeof ClubCsvName]


export const ClubJaName = {
    'XXX': 'その他',
    'PT': 'パター',
    '9WG': '60°',
    '8WG': '58°',
    '7WG': '56°',
    '6WG': '54°',
    '5WG': '52°',
    '4WG': '50°',
    'LW': 'ピッチングウェッジ',
    'SW': 'サンドウェッジ',
    'PW': 'ロブウェッジ',
    '9I': '9 IRON',
    '8I': '8 IRON',
    '7I': '7 IRON',
    '6I': '6 IRON',
    '5I': '5 IRON',
    '4I': '4 IRON',
    '3I': '3 IRON',
    '2I': '2 IRON',
    '1I': '1 IRON',
    '9UT': '9 UT',
    '8UT': '8 UT',
    '7UT': '7 UT',
    '6UT': '6 UT',
    '5UT': '5 UT',
    '4UT': '4 UT',
    '3UT': '3 UT',
    '2UT': '2 UT',
    '1UT': '1 UT',
    '9W': '9 WOOD',
    '8W': '8 WOOD',
    '7W': '7 WOOD',
    '6W': '6 WOOD',
    '5W': '5 WOOD',
    '4W': '4 WOOD',
    '3W': '3 WOOD',
    '2W': '2 WOOD',
    'DR': 'ドライバー',
} as const

export type ClubJaNames = typeof ClubJaName[keyof typeof ClubJaName]

export const ClubCode = {
    'XXX': undefined,
    'PT': undefined,
    '9WG': undefined,
    '8WG': undefined,
    '7WG': undefined,
    '6WG': undefined,
    '5WG': undefined,
    '4WG': undefined,
    'LW': undefined,
    'SW': undefined,
    'PW': undefined,
    '9I': undefined,
    '8I': undefined,
    '7I': undefined,
    '6I': undefined,
    '5I': undefined,
    '4I': undefined,
    '3I': undefined,
    '2I': undefined,
    '1I': undefined,
    '9UT': undefined,
    '8UT': undefined,
    '7UT': undefined,
    '6UT': undefined,
    '5UT': undefined,
    '4UT': undefined,
    '3UT': undefined,
    '2UT': undefined,
    '1UT': undefined,
    '9W': undefined,
    '8W': undefined,
    '7W': undefined,
    '6W': undefined,
    '5W': undefined,
    '4W': undefined,
    '3W': undefined,
    '2W': undefined,
    'DR': undefined,
} as const

export type ClubCodes = keyof typeof ClubCode