import _ from "lodash";
import { Club, Driver, EightIron, EightUtility, EightWedge, EightWood, FiveIron, FiveUtility, FiveWedge, FiveWood, FourIron, FourUtility, FourWedge, FourWood, LobWedge, NineIron, NineUtility, NineWedge, NineWood, OneIron, OneUtility, Other, PitchingWedge, Putter, SandWedge, SevenIron, SevenWedge, SevenWood, SixIron, SixUtility, SixWedge, SixWood, ThreeIron, ThreeUtility, ThreeWood, TwoIron, TwoUtility, TwoWood, } from "./club";
import { ClubCode, ClubCsvName } from "./csvType";


export const clubInstances: { [K in ClubCode]: Club } = {
    'XXX': new Other(),
    'PT': new Putter(),
    '9WG': new NineWedge(),
    '8WG': new EightWedge(),
    '7WG': new SevenWedge(),
    '6WG': new SixWedge(),
    '5WG': new FiveWedge(),
    '4WG': new FourWedge(),
    'LW': new LobWedge(),
    'SW': new SandWedge(),
    'PW': new PitchingWedge(),
    '9I': new NineIron(),
    '8I': new EightIron(),
    '7I': new SevenIron(),
    '6I': new SixIron(),
    '5I': new FiveIron(),
    '4I': new FourIron(),
    '3I': new ThreeIron(),
    '2I': new TwoIron(),
    '1I': new OneIron(),
    '9UT': new NineUtility(),
    '8UT': new EightUtility(),
    '7UT': new SevenWood(),
    '6UT': new SixUtility(),
    '5UT': new FiveUtility(),
    '4UT': new FourUtility(),
    '3UT': new ThreeUtility(),
    '2UT': new TwoUtility(),
    '1UT': new OneUtility(),
    '9W': new NineWood(),
    '8W': new EightWood(),
    '7W': new SevenWood(),
    '6W': new SixWood(),
    '5W': new FiveWood(),
    '4W': new FourWood(),
    '3W': new ThreeWood(),
    '2W': new TwoWood(),
    'DR': new Driver(),
}

export const csvClubNameToClubCode: { [Key in ClubCsvName]: ClubCode } = {
    'その他': 'XXX',
    'パター': 'PT',
    '60°': '9WG',
    '58°': '8WG',
    '56°': '7WG',
    '54°': '6WG',
    '52°': '5WG',
    '50°': '4WG',
    'ピッチングウェッジ': 'PW',
    'サンドウェッジ': 'SW',
    'ロブウェッジ': 'LW',
    '9 iron': '9I',
    '8 iron': '8I',
    '7 iron': '7I',
    '6 iron': '6I',
    '5 iron': '5I',
    '4 iron': '4I',
    '3 iron': '3I',
    '2 iron': '2I',
    '1 iron': '1I',
    '9 ut': '9UT',
    '8 ut': '8UT',
    '7 ut': '7UT',
    '6 ut': '6UT',
    '5 ut': '5UT',
    '4 ut': '4UT',
    '3 ut': '3UT',
    '2 ut': '2UT',
    '1 ut': '1UT',
    '9 wood': '9W',
    '8 wood': '8W',
    '7 wood': '7W',
    '6 wood': '6W',
    '5 wood': '5W',
    '4 wood': '4W',
    '3 wood': '3W',
    '2 wood': '2W',
    'ドライバー': 'DR',
} as const


